spring:
  data:
    mongodb:
      #uri: mongodb+srv://root:password007@cluster0-cjhrd.gcp.mongodb.net/scorpious-demo?retryWrites=true&w=majority
      username: user
      password: password@123
      database: event_db
      host: localhost
      port: 27017
      auto-index-creation: true
  datasource:
#    url: jdbc:mysql://localhost:3306/registration
    url: jdbc:mysql://localhost:3307/registration
    username: root
    password: 1234
  #    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: debug
  mail:
    host: smtp.mailersend.net
    username: MS_qQOdgh@trial-v69oxl5nk8rl785k.mlsender.net
    #    password: sfsh lsgj qddi pzgi
    password: 8Xw5uVS366WwxbA7
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true